Add tutorial on removing the address field from person
se-edu/addressbook-level3 pull request #14
Opened 2019-06-30 14:07 UTC by j-lum

2019-07-01 03:02 UTC, damithc requested changes
Looks good 👍 
Some suggestions added.

2019-07-01 03:02 UTC, damithc commented on docs/tutorial/RemovingFields.adoc
> +{empty} +
Let's stick to SE quotes only :-)

2019-07-01 03:02 UTC, damithc commented on docs/tutorial/RemovingFields.adoc
> +Consider refactoring the existing `Person` model to suit your use case.
Removing a field may not be strictly _refactoring_

2019-07-01 03:02 UTC, damithc commented on docs/tutorial/RemovingFields.adoc
> +`Safe Delete` through the menu.
>Select the `Address` class

Select where?

2019-07-01 03:02 UTC, damithc commented on docs/tutorial/RemovingFields.adoc
> +Unfortunately, there are usages of `Address` that IntelliJ IDEA cannot identify. Let's fix them.
fix -> remove?

2019-07-01 03:02 UTC, damithc commented on docs/tutorial/RemovingFields.adoc
> +
Would a project-wide text search help here? i.e., Ctrl+Shift+F

2019-07-01 03:02 UTC, damithc commented on docs/tutorial/RemovingFields.adoc
> +application to add dummy values. Don't forget to modify a copy of valid data to produce invalid data!
The reader might not be able to understand this paragraph (i.e., it assumes some background knowledge the reader might not have). Perhaps we should have some description of how testing and test data works somewhere?

2019-07-01 03:02 UTC, damithc commented on docs/tutorial/RemovingFields.adoc
> +up test data and references to `Address` in the documentation.
reader: If the tests are passing, why there is a need to clean up further? 🤔

2019-07-18 07:42 UTC, j-lum commented
Closing this in favor of the newer PRs.

2019-07-18 07:42 UTC, closed without merging