Show warning when ignoring repeated parameters
se-edu/addressbook-level3 pull request #176
Opened 2023-05-17 21:02 UTC by Eclipse-Dominator

Currently, repeated occurrences of the same parameter in a command are being ignored without any notification to the user. This can lead to potential user errors going unnoticed, especially when using the wrong parameter prefix multiple times.

This commit introduces a friendly warning system that alerts the user when a parameter is being ignored. Now, if a parameter is repeated in a command, all occurrences except the last one will trigger a warning message, ensuring that the user is aware of any unintentional mistakes or typos.

Let's provide a better user experience by catching and notifying them of ignored parameters, improving the overall usability and preventing potential errors.

2023-05-18 07:41 UTC, damithc requested changes
I'm a bit hesitant about this approach because,
1. It doesn't inform the user which parameter is duplicated
2. It doesn't differentiate between one parameter being duplicated vs multiple parameters being duplicated

Perhaps we should explore alternatives to see if there is a better way?

2023-05-18 07:41 UTC, damithc commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +            + "applying the latest change.\n";
modification -> modifications?
Is it correct to say _modifications_ i.e., are these strictly modifications or something else? Similarly, 'latest change' doesn't seem like the correct phrase.

2023-05-18 09:18 UTC, Eclipse-Dominator commented
Hmm, alright, I chose this initially as I felt this will require the least amount of changes but I will come up with a secondary approach to display which field has been duplicated.

2023-05-18 09:52 UTC, damithc commented
> Hmm, alright, I chose this initially as I felt this will require the least amount of changes but I will come up with a secondary approach to display which field has been duplicated.

Yup, this may still be the best option but it's better to explore other options before making a decision.

2023-06-02 01:33 UTC, Eclipse-Dominator commented
I have created a secondary PR to show an alternative approach in #181

2023-06-07 20:17 UTC, Eclipse-Dominator commented
Repeated Parameters show warning: #176 
Repeated Parameters show warning of repeated prefixes: #181 
Repeated Parametes treated as errors: #190

2023-06-12 17:19 UTC, damithc commented
Closing in favor of #190

2023-06-12 17:19 UTC, closed without merging