[#166] Bump javafx to version 11.0.2
se-edu/addressbook-level3 pull request #177
Opened 2023-05-18 05:36 UTC by Eclipse-Dominator

Fixes #166

2023-05-18 07:21 UTC, damithc requested changes
Commit 1:
The commit message (subject or body) does not specify what is the actual issue being fixed. 
Include a brief description. In addition, if there is an online description of the problem, we can give a link.
`described in JDK-8210411 presents a compatibility issue for users using` is longer than 72 chars.

Commit 2:
Let's not sneak in unrelated changes into a PR. That reduces the searchability of the PR/issue tracker.

2023-05-18 13:51 UTC, damithc reviewed
I assume you tested this to confirm the fix works (I didn't).

Separately, check our JavaFX guide (https://se-education.org/guides/tutorials/javaFx.html) and the Grade guide to see if they need updating too.

Commit message subject is too generic?

2023-05-18 13:53 UTC, damithc commented
@zhongfu I remember you did some investigation into this problem earlier. If you are free, your inputs are welcome.

2023-06-01 16:51 UTC, zhongfu approved these changes
Looks good to me; I can confirm that this PR allows AB3 to run on Wayland without needing to force the use of X11 explicitly

(p.s. sorry for the late reply -- I missed this somehow)

2023-06-02 06:00 UTC, damithc commented
@zhongfu thanks very much for checking. :+1:

2023-06-03 17:09 UTC, damithc approved these changes

2023-06-03 17:21 UTC, merged