Tutorial: Port code for RemarkCommand
se-edu/addressbook-level3 pull request #20
Opened 2019-07-18 06:49 UTC by j-lum

Now that the code base for AB3 has stabilized, let's port the removed tutorial from AB4 to AB3.
This should belong on its own branch. 

This commit does not contain the tutorial adoc. I'll be opening a PR to merge that into master.

2019-07-19 05:35 UTC, damithc commented
I wonder if the initial steps can be even smaller. e.g., start with a simpler form of the command `remark` (not `remark 2 r/ good`). This will result in a smaller first commit.

On a related note, the current breakdown still feels like written by someone who knows the model solution, whereas the reader doesn't have that kind of expertise. Hence, the steps given may sound 'magical' to the reader (i.e., there is an empathy gap between the writer and the reader, which makes it harder for the reader to connect with the content). 
Keep in mind that we are not only training students to work with AB-3 code base, but also training them _how to use a strategy of 'tiny increments' when working in an unfamiliar code base_. The latter has more value but requires more effort in writing. For example, we should also explain the thought process in a way that can be generalized (`trace through a part that is similar to our target feature` instead of `trace through the delete command`)

2019-07-19 05:39 UTC, j-lum commented
From the code, we start from 
1. recognizing `remark` and ignoring everything else
1. recognizing the whole argument string
1. parsing the string to obtain more useful data

So I don't think the code needs to change, maybe we can emphasize the build up a bit more in the tutorial?

2019-07-19 05:51 UTC, damithc commented
> So I don't think the code needs to change, maybe we can emphasize the build up a bit more in the tutorial?

The first commit has more code than necessary. e.g.,
* any mention of prefix
* an elaborate help message
* test case

These are things an experienced AB programmer would include in the first step (because she knows these will be needed eventually) but not a newcomer.

2019-07-19 05:56 UTC, j-lum commented
I'm writing a new bridging section between the intro and the first bits to code to help the students case out the problem and break it down into logical components. From there we can re-evaluate how we want to structure the commits since the old tutorial (and its code) was meant to be the model answer.

2019-07-19 07:35 UTC, j-lum commented
Added a new intermediate step before `Logic: Teach the app to accept 'remark' but do nothing `.

The rationale was that students with little exposure to the code base isn't going to write standard-compliant code right from the code and we should ease them into the process.

2019-07-20 03:18 UTC, damithc requested changes
2nd step needs to be simplified further as it contains things the reader will not see the need for. Plus, it needs to match the first step: currently, the first step creates a Result object and the second step switches to the Exception route.

2019-07-20 03:18 UTC, damithc commented on src/main/java/seedu/address/logic/commands/RemarkCommand.java
> +import static seedu.address.logic.parser.CliSyntax.PREFIX_REMARK;
Not needed for this step

2019-07-20 03:18 UTC, damithc commented on src/main/java/seedu/address/logic/commands/RemarkCommand.java
> +            + PREFIX_REMARK + "Likes to swim.";
not needed for this step

2019-08-21 14:59 UTC, damithc commented
Is there a 1-1 mapping between the commits here and the sections in the tutorial? It's ideal if there is. In that case, section names and commit subjects should match closely.

2019-08-25 02:16 UTC, damithc commented
Let's move to the next iteration

2019-09-06 08:02 UTC, j-lum commented
Not all commit titles are strict 1-1 matches but they are close enough with some minor differences in grammar. 

Going to shove this through for tutorial on week 6.

2019-09-06 08:04 UTC, closed without merging