Upgrade plant uml new theme
se-edu/addressbook-level3 pull request #202
Opened 2023-07-27 06:03 UTC by Eclipse-Dominator

Alternative to #201 where the new default theme is used instead of the old rose theme.

PlantUML(1.2023.2) introduced a change in behavior when rendering
diagrams. This causes some of the diagrams to be rendered incorrectly or
fail to compile. Diagrams are also being rendered in a different theme
due to a change in the default color theme.

Therefore, some of the PlantUML code and images need to be updated to
ensure functionality and consistency. The old color scheme will also be
applied as some of the manual color changes are based on it.

Let's
 * update PlantUML code to ensure they can be rendered properly
 * update diagrams to use the original theme to fit the manual theme
   changes
 * update the diagrams to ensure consistency between the PlantUML code
   and the rendered image

2023-07-27 06:47 UTC, damithc commented
@Eclipse-Dominator do you see any diagrams that is not optimal under the default theme (compared to the old theme)?

For the following, I'm not sure why the Storage component appears in a different color.
![image](https://github.com/se-edu/addressbook-level3/assets/1673303/3abe2cf0-72ba-4373-bd29-fa16f6632bf2)

But while we are at it, we can actually color each of those two boxes with a very light shade of the main color we use the same components in the architecture diagram.

2023-07-27 07:00 UTC, Eclipse-Dominator commented
I believe there is some rendering logic for Packages that contains classes and Packages that doesn't. The model package above contains a hidden class but the storage package doesn't. This causes the change in rendering.

> But while we are at it, we can actually color each of those two boxes with a very light shade of the main color we use the same components in the architecture diagram.

Mainly it would be the UndoRedoState diagrams.
![image](https://github.com/se-edu/addressbook-level3/assets/4567895/091c9e2b-4881-4cfa-9541-1c8535341ee6)

The main differences between the 2 themes are mainly:
- Classes are no longer colored
- Arrows and lines are black by default (previously red)
- Change in the color of `note`

2023-07-27 07:28 UTC, damithc commented
> The main differences between the 2 themes are:
> 
> * Classes are no longer colored
> * Borders, arrows and lines are black by default (previously red)
> * Change in the color of `note`

Personally, I think the old theme is slightly easier to read. But given that using the defaults is less work, I'm fine to switch to the new theme despite the slight loss of readability.

2023-07-27 07:49 UTC, Eclipse-Dominator commented
> Personally, I think the old theme is slightly easier to read. But given that using the defaults is less work, I'm fine to switch to the new theme despite the slight loss of readability.

Generally, it will be the same amount of work as all the formatting is found in `style.puml` as students just need to include `!include style.puml` or `skin rose` in their files so it's around the same. 

I will make some additional changes to this version to fit the new theme.

2023-07-29 11:04 UTC, damithc reviewed
Looks good. 
The following part of the commit message can be shortened as it is mostly stating the obvious:
```
Therefore, some of the PlantUML code and images need to be updated to
ensure functionality and consistency.

Let's
 * update PlantUML code to ensure they can be rendered properly
 * update the diagrams to ensure consistency between the PlantUML code
   and the rendered image
```
Something like this?
```
Let's update the PlantUML diagrams accordingly.
```

2023-07-29 11:04 UTC, damithc commented
@se-edu/tech-team-level1 for your review ...

2023-07-29 12:30 UTC, dlimyy reviewed
Overall, LGTM! Just one minor suggestion

2023-07-29 12:30 UTC, dlimyy commented on docs/images/ModelClassDiagram.png
For the new image, it would be good if the association role `filtered` can be shifted to the association pointing from ModelManager to Person(similar to the old image) since it is the ModelManager that contains the filtered list of `Person`.

2023-07-29 13:31 UTC, Eclipse-Dominator commented on docs/images/ModelClassDiagram.png
Added an invisible class to separate the 2 labels.

2023-07-29 17:22 UTC, SPWwj requested changes
The PR looks good, as it standardizes the hexadecimal color from 5 to 6 digits. However, due to this change, the style of some diagrams may not look as good as before. It would be better if we could adjust the style to make the diagrams easier to read.

1. I've noticed that previously all labels were bold, but in the new version, they are not. It might be beneficial to restore the bold formatting for better readability.

2. The default color of the lines is not the same as in the previous version, but I think this is acceptable as it doesn't significantly impact the understanding of the diagrams.

2023-07-29 17:22 UTC, SPWwj commented on docs/images/CommitActivityDiagram.png
The style of this diagram is slightly different. Can we adjust the CSS to make the text and nodes stand out, making them easier to read?

2023-07-29 17:22 UTC, SPWwj commented on docs/images/LogicClassDiagram.png
The original diagram had better contrast and was easier to read. Can we adjust the CSS to make it similar to the original diagram?

2023-07-30 02:12 UTC, Eclipse-Dominator commented on docs/images/LogicClassDiagram.png
I wasn't able to directly make font thicker but I compensated by bumping the font size slightly to make the font appear clearer.

2023-08-04 14:38 UTC, merged