Refine UG to state that extra parameters are ignored
se-edu/addressbook-level3 pull request #67
Opened 2020-12-05 09:50 UTC by mehak24k

Fixes #60

2020-12-12 07:04 UTC, damithc commented
Thanks for the fix @mehak24k 
Can you submit an update as per the bot comment above and also provide a full commit message as per https://se-education.org/guides/conventions/git.html ?

2020-12-14 03:45 UTC, mehak24k commented
> Thanks for the fix @mehak24k
> Can you submit an update as per the bot comment above and also provide a full commit message as per https://se-education.org/guides/conventions/git.html ?

Thank you for the feedback, I have refined the commit message and submitted an update with the bot.

2020-12-14 07:31 UTC, damithc requested changes
Some comments added.

2020-12-14 07:31 UTC, damithc commented on docs/UserGuide.md
> +* Extra parameters will be ignored.
Missing `<br>`?

2020-12-14 07:31 UTC, damithc commented on docs/UserGuide.md
> +  e.g. if the command specifies `help 123`, it will be interpreted as `help`.
At this point, the reader doesn't know the correct format of the help command, and hence, may not realize that `123` is extraneous.

2020-12-14 07:31 UTC, damithc commented on docs/UserGuide.md
> +* Extra parameters will be ignored.
Is _extraneous_ a better choice of words here? Or _irrelevant_?

2020-12-14 07:31 UTC, damithc commented on docs/UserGuide.md
Commit message:
* Make the subject more specific
* The second sentence can be omitted as it doesn't seem to add much value.

2021-01-04 08:14 UTC, iamjamestan requested changes

2021-01-04 08:14 UTC, iamjamestan commented on docs/UserGuide.md
> +* Extra parameters will be ignored.
Extra parameters are only ignored in **commands that take in no parameters**, such as `help`, `list`, `exit` and `clear`. For the other commands, extra parameters will either throw an error or result in the [last most parameter to be accepted](https://github.com/se-edu/addressbook-level3/issues/58), instead of just simply being ignored.
 
To be more specific, perhaps this line can be revised to:
"Extraneous parameters for commands that do not take in parameters (such as `help`, `list`, `exit` and `clear`) will be ignored."?

2021-01-04 08:24 UTC, damithc commented on docs/UserGuide.md
> +* Extra parameters will be ignored.
Good point @iamjamestan 
As this PR seems to be stalled, do you mind creating a new PR with the suggested change?

2021-01-11 01:01 UTC, damithc commented on docs/UserGuide.md
> +* Extra parameters will be ignored.
@iamjamestan reminder

2021-02-02 00:00 UTC, iamjamestan commented on docs/UserGuide.md
> +* Extra parameters will be ignored.
@damithc Hi prof, sorry for the late reply. Will do so soon.

2021-02-03 15:18 UTC, damithc commented
Closing as it is fixed by another PR

2021-02-03 15:18 UTC, closed without merging